### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by ctmattice** [geneb/ScarletDME#10]
Gene,

Made some changes to the Make file. Then following is output from my copy.
diff --git a/Makefile b/Makefile
index 0ce6595..b8b169e 100644
--- a/Makefile
+++ b/Makefile
@@ -182,15 +182,23 @@ sysseg.o: sysseg.c revstamp.h
 
 .PHONY: clean distclean install datafiles
 
-install:  
+install:
        @echo Installing to $(INSTROOT)
        @test -d $(INSTROOT) || mkdir $(INSTROOT)
        @test -d $(INSTROOT)/bin || mkdir $(INSTROOT)/bin
        @for qm_prog in $(GPLBIN)*; do \
-         install -m 775 -o qmsys -g qmusers $$qm_prog $(INSTROOT)/bin; \
+               install -m 775 -o qmsys -g qmusers $$qm_prog $(INSTROOT)/bin; \
        done
        @chmod -R 775 $(INSTROOT)
 
+#      For now copy qmconfig to /etc/scarlet.conf
+       @echo Writing scarlet.conf file
+       @cp $(main)qmconfig /etc/scarlet.conf
+       @chmod 644 /etc/scarlet.conf
+
+#      Create symbolic link if it does not exist
+       @test -f /usr/bin/qm || @ln -s /usr/qmsys/bin/qm /usr/bin/qm
+
 datafiles:
        @echo Installing data files...
        @cp -r $(MAIN)ACCOUNTS/ $(INSTROOT)/ACCOUNTS
(END)

Would be interested in helping convert to the 64 bit version where I can.

**Comment by geneb** [comment]
I just committed a pull request for a MacOS change, so you might want to make your changes to that Makefile (dev branch) and then just send me a pull request in order to merge it in.

I've exhausted my C-fu on the 64 bit side, so you're welcome to dive in.  I suspect it's either going to be really weird & obscure, or something totally trivial. ;)

g.
