### ISSUE TITLE
Login error after install

### ISSUE THREAD

**Issue by dmontaine** [geneb/ScarletDME#28]
On OpenSuse Leap, logging in from /usr/qmsys directory

Even though $LOGINS file is 775 and owned by qmsys:qmusers

when attempting  to login get
Error 3818 writing to $LOGINS

error continues after changing $LOGINS to 777
error resolves after changing all files recursively in qmsys to 777

**Comment by geneb** [comment]
This is related to the current user not being recognized as being in the qmusers group.  Logging out of the system and logging back in, or rebooting will resolve this.  You can get around it by issuing "su <your userid> in order to avoid logging out or rebooting.

I've updated the info/setup.txt file with better instructions.
