### ISSUE TITLE
$CRYPTO object code issues 64 bit

### ISSUE THREAD

**Issue by dmontaine** [geneb/ScarletDME#31]
LIST.KEYS VOC
00001EF4: Unable to load '$CRYPTO' object code
 in $CPROC

**Comment by geneb** [comment]
This happens because all of the encryption features were stripped from OpenQM before the GPL source release.  They did a good job of crippling the functionality, but did a piss poor job of cleaning up the mess.  ENCRYPT.FILE also references $CRYPTO, which we have no source code for.  

I found the code that OpenQM used to do the heavy lifting for the encryption process - I forked the repo (it was written by a third party as an open source project) and can be found as "aes" in my git repository.  

I suspect the actual reason for pulling the encryption features is due to the aes license not being compatible with the GPLv2 - I haven't checked though.  It would have been nice to at least been left the QMBasic code side in order to assist re-implementation.

I'm going to close this as "wontfix" and at some point, we'll get a new issue created that can tackle it as a project.

**Comment by dmontaine** [comment]
:DELETE.KEY  (from QMSYS)
00001EF4: Unable to load '$CRYPTO' object code
 in $CPROC

**Comment by dmontaine** [comment]
:CREATE.KEY
00001EF4: Unable to load '$CRYPTO' object code
 in $CPROC

**Comment by dmontaine** [comment]
:ENCRYPT.FILE
00001EF4: Unable to load '$CRYPTO' object code
 in $CPROC
